POST http://localhost:8000/accounts
content-type: application/json

{
    "owner": "sample2",
    "currency": "EUR"
}


###

GET http://localhost:8000/accounts/2

###

GET http://localhost:8000/accounts?page_id=1&page_size=2
###


GET https://localhost:8000/accounts
    ?page=0
    &pageSize=5
