POST http://localhost:8000/accounts
content-type: application/json

{
    "owner": "unique",
    "currency": "USD"
}

###
POST http://localhost:8000/users
content-type: application/json

{
    "username": "aaashi",
    "password": "abcdefghi",
      "full_name": "aashsijh",
          "email": "uniqueldd@gmail.com"
}

###
POST http://localhost:8000/users/login
content-type: application/json

{
    "username": "unique",
    "password": "abcdefghi"
}


###
GET http://localhost:8000/users/adshybnub7

###

GET http://localhost:8000/accounts/45

###

GET http://localhost:8000/accounts?page_id=3&page_size=3
###


POST http://localhost:8000/transfers
content-type: application/json

{
    "from_account_id": 102,
    "to_account_id": 45,
    "amount": 100,
    "currency": "EUR"
}

