POST http://localhost:8000/accounts
content-type: application/json

{
    "owner": "adshybnub7",
    "currency": "USD"
}

###
POST http://localhost:8000/users
content-type: application/json

{
    "username": "adsub7",
    "password": "abcdefghi",
      "full_name": "aashsijh",
        "email": "USD@gmail.com"
}


###
GET http://localhost:8000/users/adshybnub7

###

GET http://localhost:8000/accounts/45

###

GET http://localhost:8000/accounts?page_id=3&page_size=3
###


POST http://localhost:8000/transfers
content-type: application/json

{
    "from_account_id": 7,
    "to_account_id": 8,
    "amount": 100,
    "currency": "gfv"
}

