services:
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simplebank
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - dbsource=postgresql://root:password@postgres:5432/simplebank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for-it.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]



