# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
      
    services:
      postgres:
        # Docker Hub image
        image: postgres:16.0-alpine3.18
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: password
          POSTGRES_DB: simplebank

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.0'

      - name: Check out code into go module dir
        uses: actions/checkout@v4

      - name: Install migrate tool cli
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.1/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/
          which migrate

      - name: Run Migrations
        run: make migrateup


      - name: Test
        run:  make test
